export const POKEMON_TYPE_COLORS = {
   normal: '#A8A878',
   fighting: '#C03028',
   flying: '#A890F0',
   poison: '#A040A0',
   ground: '#E0C068',
   rock: '#B8A038',
   bug: '#A8B820',
   ghost: '#7C538C',
   steel: '#B8B8D0',
   fire: '#FC6D6D',
   water: '#77BEFE',
   grass: '#4AD0B1',
   electric: '#FFCE4C',
   psychic: '#F85888',
   ice: '#98D8D8',
   dragon: '#7038F8',
   dark: '#705848',
   fairy: '#EE99AC',
};

const pokemonTypeNames = [
   'normal',
   'fighting',
   'flying',
   'poison',
   'ground',
   'rock',
   'bug',
   'ghost',
   'steel',
   'fire',
   'water',
   'grass',
   'electric',
   'psychic',
   'ice',
   'dragon',
   'dark',
   'fairy',
] as const;

export type POKEMON_TYPE_NAMES = typeof pokemonTypeNames[number];
